const catalog = [
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 0,
    idShow: 32058,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 1,
    idShow: 71717,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 2,
    idShow: 79800,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 3,
    idShow: 16400,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 4,
    idShow: 16964,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 5,
    idShow: 14425,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 6,
    idShow: 14652,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 7,
    idShow: 14205,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 8,
    idShow: 87594,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 9,
    idShow: 78025,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 10,
    idShow: 87978,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 11,
    idShow: 91472,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 12,
    idShow: 80005,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 13,
    idShow: 45127,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 14,
    idShow: 99872,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 15,
    idShow: 80225,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 16,
    idShow: 13287,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 17,
    idShow: 14581,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 18,
    idShow: 85481,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 19,
    idShow: 15379,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 20,
    idShow: 79513,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 21,
    idShow: 96325,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 22,
    idShow: 96847,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 23,
    idShow: 25010,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 24,
    idShow: 87975,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 25,
    idShow: 85749,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 26,
    idShow: 27848,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 27,
    idShow: 84765,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 28,
    idShow: 39754,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 29,
    idShow: 71654,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 30,
    idShow: 18765,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 31,
    idShow: 38146,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 32,
    idShow: 42510,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 33,
    idShow: 28577,
  },
  {
    name: "Подарунковий золотий зливок Argor-Heraeus 5",
    photo: "photos/goldTry.jpg",
    buyIngPricePerGramm: "147.20$",
    sellingPerGramm: "162.54$",
    weight: "5Г",
    metal: "Золото",
    country: "Швейцарія",
    mader: "Argor-Heraeus",
    status: "Є в наявності",
    id: 34,
    idShow: 27481,
  },
];

let toPushInner = [];

catalog.forEach((goldpeace) => {
  toPushInner.push(`<li>
    <img class="imgShowlist" src="${goldpeace.photo}" alt="#" />
    <h2 class="descriptionList">
      ${goldpeace.name}
    </h2>
    <div class="flexItem">
      <p>Курс покупки</p>
      <p>${goldpeace.buyIngPricePerGramm}/г</p>
    </div>
    <a href="makeorder.html" class="buyList">Детальніше</a><br />
    <a href="makeorder.html" class="buyList">Купити</a>
  </li>`);
});

const buyBtn = document.querySelector(".buy");

const listGoldCatalog = document.querySelector(".listGoldCatalog");

listGoldCatalog.innerHTML = toPushInner.join("");

// console.log(toPushInner.join(''));
